after_success:
  - "npm run coverage"
cache:
  directories:
    - node_modules
language: node_js
node_js:
  - stable
install:
  - npm install
notifications:
  email: false
script:
  - "npm run test"
sudo: false
